### ISSUE TITLE
Use emmet on Tsx files.

### ISSUE THREAD

**Issue by jR0driguez** [troy351/emmet-monaco-es#103]
Hi,

I'm trying to add the emmet-monaco-es dependency on a custom Monaco implementation that uses the monaco-editor dependency directly, without react.

I only found an example of use it on [sandbox ](https://codesandbox.io/s/monaco-with-emmet-forked-6dnyp8?file=/src/App.js) that only renders an HTML file. But I'm trying to use it with react files and does not work properly. The autocomplete only shows typescript values, not HTML tags.
How you see in the next image:
![monaco](https://user-images.githubusercontent.com/7352361/164001490-ce07805e-568a-4220-8bde-e6c0bdcd09f7.png)

My implementation is the next one:
```ts      monaco.languages.typescript.typescriptDefaults.setDiagnosticsOptions({
            noSemanticValidation: false,
            noSyntaxValidation: false
        });

        monaco.languages.typescript.typescriptDefaults.setCompilerOptions({
            experimentalDecorators: true,
            allowSyntheticDefaultImports: true,
            jsx: this.monaco.languages.typescript.JsxEmit.React,
            moduleResolution: monaco.languages.typescript.ModuleResolutionKind.NodeJs,
            allowNonTsExtensions: true,
            reactNamespace: 'React',
            // typeRoots: ["node_modules/@types"],
            target: monaco.languages.typescript.ScriptTarget.ES2020,
        })
        const instance =  monaco.editor.create(selector, {
            fontSize: 12,
            formatOnPaste: true,
            formatOnType: true,
            theme: vs-dark,
            scrollbar: {
                alwaysConsumeMouseWheel: false
            },
            automaticLayout: true,
            fixedOverflowWidgets: true,
            mouseWheelZoom: true
        });
      emmetHTML(this.monaco, ['html', 'tsx', 'jsx']);
      //emmetJSX(this.monaco, ['html', 'tsx', 'jsx']); // I test this option too.
      emmetJSX(this.monaco);
        ;`


My editor works well but the emmet functionality is not ok.

What more is needed to do?

**Comment by troy351** [comment]
`emmetJSX(this.monaco);` should just works

FYI, initialize emmet should BEFORE all monaco editor instance creation.
I've added this to README

**Comment by jR0driguez** [comment]
> `emmetJSX(this.monaco);` should just works
> 
> ~FYI, initialize emmet should BEFORE all monaco editor instance creation. I've added this to README~
> 
> I think you forgot to specify the language in `monaco.editor.create`. Also, `tsx`, `jsx` are invalid languages, `typescript` and `javascript` should be used instead

Thanks a lot. I change my emmetJSX line to this:
`emmetJSX(this.monaco, ['html', 'typescript', 'javascript']);`

And it's working now. The thing is since the function name includes the JSX suffix, I thought was not necessary to include the languages.

Thanks!
