### ISSUE TITLE
Support mdx

### ISSUE THREAD

**Issue by remcohaszing** [troy351/emmet-monaco-es#104]
I’m interested in support for [MDX](https://mdxjs.com).

I’ve already [created basic language support](https://github.com/microsoft/monaco-editor/pull/3096) to Monaco Editor.

I fiddled a bit locally and tried adding the `mdx` key using same consifuration `javascript` in https://github.com/troy351/emmet-monaco-es/blob/9dfbeb0046b56b34b154a874a5c795f44359e032/src/index.ts#L13-L27

But I couldn’t get it to work. Could you add it or help me troubleshoot this?

**Comment by troy351** [comment]
the key part is [here](https://github.com/troy351/emmet-monaco-es/blob/master/src/abbreviationActions.ts#L9), emmet only triggers when token valid.

**Comment by troy351** [comment]
Closing now since new version was released
