### ISSUE TITLE
monaco `0.35.0` support

### ISSUE THREAD

**Issue by CetinSert** [troy351/emmet-monaco-es#108]
`emmet-monaco-es` `5.1.2` does not work with `monaco` `0.35.0`

**Comment by troy351** [comment]
I'll fix it next Monday :)

**Comment by troy351** [comment]
It seems the source code of `monaco-editor@0.35.0` mangled `private` and `protected` properties of `class` which was used inside this project https://github.com/microsoft/vscode-discussions/discussions/257 https://github.com/microsoft/vscode/pull/166126.
I can somehow find the mangled property but it not seems promising.

**Comment by CetinSert** [comment]
@troy351 – does `monaco` not expose enough documented APIs to implement `emmet` without access to `private`/`protected` properties?

**Comment by CetinSert** [comment]
https://github.com/microsoft/vscode-discussions/discussions/257#discussioncomment-4788068
> we do have source map information for mangled properties and anyone can use those to reverse map the non-mangled names. Fundamentally, patching VS Code is still possible it just got harder because names are shortened (for the reasons outlined above). Generally, extension relying on patching internals are tolerated but not supported. Doing so would put us into a position where absolutely no change is possible anymore. Future engineering work, like the upcoming AMD to ESM migration, can cause a similar swirl and we will not pause them.

**Comment by troy351** [comment]
In order to trigger emmet at the correct location, token information was needed. And internal api was used to get token in a performant way. Public api can only tokenize whole file which is very slow in larger files.

**Comment by troy351** [comment]
v5.2.0 was release by switching to mangled property name, could be broken in next monaco-editor release
