### ISSUE TITLE
monaco `0.37.0` support

### ISSUE THREAD

**Issue by CetinSert** [troy351/emmet-monaco-es#109]
Despite https://github.com/troy351/emmet-monaco-es/commit/7e3f116de4d89c898b4b07b384246d4bfc1c874f,
`emmet-monaco-es` `5.2.1` does not work with `monaco` `0.37.0` ❌;
`emmet-monaco-es` `5.2.1` does work with `monaco` `0.36.1` ✔️ and `0.36.0` ✔️.

**Comment by troy351** [comment]
I'll fix it tomorrow :)

**Comment by troy351** [comment]
It seems mangled props was back 😆 https://github.com/microsoft/vscode/pull/177223

**Comment by troy351** [comment]
[New Version](https://github.com/troy351/emmet-monaco-es/releases/tag/5.2.2) released

**Comment by CetinSert** [comment]
@troy351 – what would now be the equivalent of

```js
i.m.getContribution('editor.contrib.suggestController')?.widget?.value?.X?.(true);
```

where `i.m` is a monaco instance?

I am trying to display and expand the suggestion box by default.

---

See https://github.com/troy351/emmet-monaco-es/issues/107

**Comment by CetinSert** [comment]
Never mind, it went back to

```js
editor.getContribution('editor.contrib.suggestController')?.widget?.value?._setDetailsVisible?.(true);
```
