### ISSUE TITLE
npm warn when installed against monaco-editor@0.18.1

### ISSUE THREAD

**Issue by Betalos** [troy351/emmet-monaco-es#11]
I am getting a warning from npm that says 
```shell
npm WARN emmet-monaco-es@4.3.1 requires a peer of monaco-editor@^0.12.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by troy351** [comment]
Because the major version of monaco-editor is `0` which means it’s not stable yet, so the version symbol `^` downgrade to `~`.
You can just ignore that warning, nothing goes wrong.





------------------ Original ------------------
