### ISSUE TITLE
How to add custom abbreviations/completions?

### ISSUE THREAD

**Issue by CetinSert** [troy351/emmet-monaco-es#110]
How can we add to
![image](https://user-images.githubusercontent.com/27027/232764595-b17bc9e4-7096-4ba8-bfb7-1693057cd295.png)
a new completion like
```
🔧 script:worker
```
```html
<script type=worker>
  async function fetch(request) {
    return new Response(request.url)
  }
</script>
```
?

Would that be handled in `emmet-monaco-es` or `monaco` itself?
Where does the completion data come from?

---

See [**`sw.rt.ht/?`**](//sw.rt.ht/?) (real-time service worker playground; with instant edge deployment!)

**Comment by CetinSert** [comment]
Do we have to use https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.CompletionItemProvider.html#provideCompletionItems?
If yes, can you provide a minimal reference/example?

**Comment by CetinSert** [comment]
@troy351 – I have found where to add the abbreviation, it was in [`emmet`](https://github.com/emmetio/emmet)!

---

Starter reference: https://stackoverflow.com/questions/14630725/does-emmet-allow-boolean-attributes

**Comment by CetinSert** [comment]
@troy351 – this is incredible! I have never been this touched by a commit! Thank you!

---

We now use this in production at [**rtcode.io**](//new.rt.ht):

![ezgif-5-15477635a2](https://user-images.githubusercontent.com/27027/233848274-5b566d78-6df4-41cc-a292-8dd31197bb15.gif)

1. Go to [**new.rt.ht**](//new.rt.ht)
2. Press <kbd>F12</kbd> to open console
3. Press <kbd>Ctrl</kbd>+<kbd>I</kbd> to focus on input
(⬇️ the video starts from here ⬇️)
4. Type `wd`; press <kbd>⏎</kbd>
5. Type `wu`; press <kbd>⏎</kbd>
6. Press <kbd>↑</kbd>/<kbd>↓</kbd> to change pathname

<details><summary>the above as video</summary>

https://user-images.githubusercontent.com/27027/233848393-74edf85e-ef5c-4f01-94ef-889090d2c341.mp4

</details>

**Comment by troy351** [comment]
Since this project was based on [vscode-emmet-helper](https://github.com/microsoft/vscode-emmet-helper) and vscode itself supports custom emmet snippets, I just bring the code I was removed back. 😄
