### ISSUE TITLE
Exports is not defined in ES module scope

### ISSUE THREAD

**Issue by simerlec** [troy351/emmet-monaco-es#112]
Hello 👋 

thank you for this library, it's really helpful for our use case.

We recently updated monaco to 0.45 and received to following error afterwards

![image](https://github.com/troy351/emmet-monaco-es/assets/5793380/0dc10da8-0438-434a-a4a4-3505d4525c3e)

any idea what's wrong here?

It's a NextJS project using pretty much the default tsconfig. Here are some relevant dependencies:

```
"monaco-editor": "0.45.0",
"emmet-monaco-es": "5.3.0",
"@monaco-editor/react": "4.6.0",
```

kind regards

**Comment by troy351** [comment]
It seems you are using the cjs version for esm import, should related to `package.json` I think.    I'll figure it out later

**Comment by simerlec** [comment]
@troy351 did you by any chance have time to look into this?

**Comment by troy351** [comment]
Could you provide a repro?
I'm not familiar with NextJS

**Comment by simerlec** [comment]
@troy351 here's a reproduction https://stackblitz.com/edit/stackblitz-starters-5m53c2?file=pages%2Findex.tsx
