### ISSUE TITLE
Does not work with monaco `0.52.0`

### ISSUE THREAD

**Issue by CetinSert** [troy351/emmet-monaco-es#114]
There is a regression caused by the latest monaco `0.52.0` release!

**Comment by CetinSert** [comment]
1. Go to [**mo.rt.ht/emmet/?**](//mo.rt.ht/emmet/?)
2. `0.52.0` → ❌
3. <kbd>↓</kbd.
4. `0.51.0` → ✔️

---

`0.52.0`
![image](https://github.com/user-attachments/assets/080adfcc-4392-49f6-afc7-51d7557e627d)

**Comment by troy351** [comment]
I'm busy recently and cannot guarantee when it can be fixed😓

**Comment by troy351** [comment]
v5.5.0 was released

**Comment by CetinSert** [comment]
Thank you!!

**Comment by Sunyuzu** [comment]
Thank you!!
