### ISSUE TITLE
How to deactivate emmet?

### ISSUE THREAD

**Issue by thekiba** [troy351/emmet-monaco-es#3]
How i can deactivate emmetHTML and emmetCSS helpers? I see you subscribe to events on monaco, but i don't see when you unsubscribe on it.

**Comment by troy351** [comment]
Unfortunately, after searching the `monaco-editor` docs, I didn't find a way to dispose added command via `editor.addCommand(key, handler)`.
see https://github.com/Microsoft/monaco-editor/issues/942

**Comment by thekiba** [comment]
Did you try something like that?

## dispose
https://github.com/Microsoft/monaco-editor/blob/master/website/playground/new-samples/interacting-with-the-editor/listening-to-key-events/sample.js

## conditionals
https://github.com/Microsoft/monaco-editor/blob/master/website/playground/new-samples/interacting-with-the-editor/adding-a-command-to-an-editor-instance/sample.js

**Comment by troy351** [comment]
The first link's code is out of date, now `editor.addCommand` returns a `commandId`, which is a string rather than a dispose function

**Comment by thekiba** [comment]
Why you closed issue?
