### ISSUE TITLE
Use both html and css

### ISSUE THREAD

**Issue by LeedaCode** [troy351/emmet-monaco-es#70]
Hi! I noticed that emmet-monaco focuses on the language setting by the monaco editor. Only when language is set to css, emmetMonaco.emmetHTML (); only take effect.
So is there any good way? Let the language of my monaco editor is set to html, the html and css of emmet take effect at the same time.

**Comment by troy351** [comment]
In monaco-editor, there is no intellisense for embed JS and CSS in HTML as VS Code does, just simple syntax highlight.
So I’m not planning to add emmet for embed CSS in HTML.
Sorry about that.

**Comment by LeedaCode** [comment]
oh okay  pity.
