### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by qutran** [troy351/emmet-monaco-es#8]
Hello! Need your help.
I'm trying to use this package, but for some reason autocompletion with emmet doesn't work with no any issue in console. Here is and example of my code.

```javascript
  import * as monaco from 'monaco-editor';
  import { emmetHTML, emmetCSS } from 'emmet-monaco-es';

  let element;

  emmetHTML(monaco);

  const editor = monaco.editor.create(element, {
    language: 'html',
    tabSize: 2,
    autoIndent: true,
    autoClosingBrackets: true,
    tabCompletion: true,
  });
```

Where element - is my dom element.

UPD.
typing: div.test - doesn't work,
but I figured that '>' triggers autocompletion

**Comment by troy351** [comment]
Please make sure monaco-editor works fine without this plugin




------------------ Original ------------------

**Comment by qutran** [comment]
Yes, it's works without plugin. And plugin is working as well but not as expected `div` + tab doesnt triggers rendering of <div></div>, but `div>` is working

**Comment by troy351** [comment]
![aaa](https://user-images.githubusercontent.com/8372385/59986175-269b7c00-9668-11e9-9911-96be4ad6ba42.gif)
In the [example](https://github.com/troy351/emmet-monaco-es/blob/master/example/index.html) page, it works

**Comment by qutran** [comment]
Yes, you are right. Probably something in my environment. I'm closing it. Thanks for response!

**Comment by 646602196** [comment]
Have you found a solution? I have the same problem

**Comment by 646602196** [comment]
> Have you found a solution? I have the same problem

Well, I found the problem. There's an error in my code
