### ISSUE TITLE
html intellisense gone after using emmet

### ISSUE THREAD

**Issue by aloksharma1** [troy351/emmet-monaco-es#88]
hi,
after applying emmet to my code, html zen coding is achieved but now i cannot get intellisense to suggest me any tags all i get is emmet abbreviation when i do ctrl+space.
for example:
1. autocomplete for head tag is not working (havent checked other tags deeply)
2. intellisense for html tags doesnt work well with emmet otherwise fine
image :
blank document intellisense 
<a href="https://ibb.co/JrhTZ6s"><img src="https://i.ibb.co/JrhTZ6s/emmet-1.png" alt="emmet-1" border="0"></a> <a href="https://ibb.co/BrYCsrx"><img src="https://i.ibb.co/BrYCsrx/emmet-2.png" alt="emmet-2" border="0"></a>

**Comment by troy351** [comment]
It's weird, this should work
<img width="678" alt="Screen Shot 2020-06-07 at 14 02 18" src="https://user-images.githubusercontent.com/8372385/83961648-c8db6080-a8c7-11ea-903d-14caaa496d49.png">

**Comment by aloksharma1** [comment]
hi,
it started working after a few reloads and full path reference to libraries, one question though when disposing monaco, should i dispose emmet first or monaco?

here is the code 

if (meditor.length > 0) {
                for (var i = 0; i < meditor.length; i++) {
                    if (meditor[i].id == el.prop("id")) {
                        if (meditor[i].editor != null) {
                            meditor[i].editor.dispose();
                            meditor[i].editor = null;
                        }
                        if (meditor[i].emmet != null) {
                            meditor[i].emmet();
                        }
                    }
                } 
            }

**Comment by troy351** [comment]
Emmet is bound to HTML / CSS language features, not each editor instance. 
So, only if you want to remove emmet from all editor instances, you should not call `dispose`, which also means you should only bind emmet once even if there are multiple editor instances and you are not able to apply emmet to only a part of editor instances.
Further more, once emmet was added, you don’t need to take care of it anymore if you are just about to create / dispose editor instances.
