### ISSUE TITLE
Error while using emmet-monaco included through a script tag 

### ISSUE THREAD

**Issue by REDEAKAA** [troy351/emmet-monaco-es#90]
So i included the plugin using the script tag option. Called the `emmetMonaco.emmetHTML();` method. Now in my editor, when i type in something i get an error **Uncaught Error: Cannot read property 'depth' of undefined**. Its really frustrating.

Thanks in advance for any help

**Comment by troy351** [comment]
Did you try the example inside this repo?





------------------ Original ------------------

**Comment by ehigiepaul** [comment]
@REDEAKAA This issue is noticeable in the latest version on monaco editor, I had to downgrade my version to get it work.

@troy351 we will need an update for the monaco editor v0.22.*

**Comment by troy351** [comment]
I'll look into it.

**Comment by REDEAKAA** [comment]
@ehigiepaul good to see that am not the only one who faced such issue!

**Comment by REDEAKAA** [comment]
@troy351 we're awaiting your reply ☺️

**Comment by troy351** [comment]
You can use `v4.5.0` now

**Comment by ehigiepaul** [comment]
> You can use `v4.5.0` now

Working thanks 👍

**Comment by REDEAKAA** [comment]
Yooo.....working perfectly now. Thanks alot 😊
