### ISSUE TITLE
How to wrap in emmet ?

### ISSUE THREAD

**Issue by rizkyramadhan** [troy351/emmet-monaco-es#91]
In vscode we have 'Wrap in emmet abbreviation' command, is this supported in emmet-monaco-es ?

**Comment by troy351** [comment]
It's not supported yet.

Since Monaco Editor was not VSCode, And there is no way to bind custom keyboard shortcuts for commands AFAIK, I think adding commands to Command Palette was not that needed.

**Comment by rizkyramadhan** [comment]
Maybe we can do that manually using executeEdit api ?

**Comment by troy351** [comment]
I can expose internal emmet api, and maybe you could add this command yourself?

**Comment by troy351** [comment]
What I really want to say is:

Select code + open Command Palette + select your command + typing emmet code

VS

Typing and expand emmet code + select code you want to wrap + drag & drop to the target position 

I think the second one is way more better and faster

**Comment by troy351** [comment]
Maybe a better way

Select code + cut + typing and expand emmet code + paste

**Comment by rizkyramadhan** [comment]
> I can expose internal emmet api, and maybe you could add this command yourself?

Yeah, this will enough.  

> Select code + open Command Palette + select your command + typing emmet code

I am get used to this flow on vscode, it's more intuitive for me...

Maybe we can put an example for implementing this ? So activation behavior will be up to the user.

**Comment by troy351** [comment]
Will add an example in this weekend

**Comment by troy351** [comment]
I've added a new example [wrap.html](https://github.com/troy351/emmet-monaco-es/blob/master/example/wrap.html).
