### ISSUE TITLE
Support emmetJS()

### ISSUE THREAD

**Issue by rizkyramadhan** [troy351/emmet-monaco-es#92]
I am currently building a jsx editor, and need to enable emmet in “javascript” language. This project currently support html and css only.

I just modified compiled version of emmet-monaco-es so that it can support jsx (I modified onComplete function and the tokenizer).

I am not confident enough to make a pull request so maybe I will put my modification here if anyone interested.

**Comment by troy351** [comment]
I think `emmetJSX` could be a better name
