### ISSUE TITLE
Not working with @monaco-editor/react

### ISSUE THREAD

**Issue by BrunoQuaresma** [troy351/emmet-monaco-es#95]
Hi, I'm trying to use it with @monaco-editor/react but does not see to be working:

```typescript
import React from "react";
import Editor from "@monaco-editor/react";
import { emmetHTML } from "emmet-monaco-es";

export default function App() {
  return (
    <Editor
      height="400px"
      defaultLanguage="html"
      theme="vs-dark"
      onMount={(_editor, monaco) => {
        emmetHTML(monaco);
      }}
    />
  );
}
```

Link to sandbox: https://codesandbox.io/s/bold-davinci-lpz8w?file=/src/App.tsx:0-330

**Comment by troy351** [comment]
`emmetHTML(monaco)` should be called **before** editor creation.

**Comment by BrunoQuaresma** [comment]
Using `beforeMount`   worked! I see it only works for `html`  language. Is there a way to make it work for `handlebars` as well?

**Comment by troy351** [comment]
I'll make it work later

**Comment by BrunoQuaresma** [comment]
Thanks.

**Comment by troy351** [comment]
New version released, check the docs

**Comment by BrunoQuaresma** [comment]
@troy351 lovely, thanks.
